import type { ProjectItem } from "@/common/types/projects";

/** Seed / fallback — real products from the web-server portfolio stack */
export const PROJECTS: ProjectItem[] = [
  {
    id: 1,
    title: "Perpustakaan UNIDA",
    slug: "perpustakaan-unida",
    description:
      "Sistem informasi perpustakaan institusi: katalog, sirkulasi, keanggotaan, dan operasional harian untuk Perpustakaan Pusat UNIDA Gontor.",
    image: "/images/projects/perpustakaan.svg",
    stacks: ["Laravel", "PHP", "MySql", "TailwindCSS"],
    is_show: true,
    is_featured: true,
    link_demo: "https://library.unida.gontor.ac.id",
    link_github: null,
  },
  {
    id: 2,
    title: "TAMS v2",
    slug: "tams-v2",
    description:
      "Teacher Academic Management System—jadwal, nilai, kehadiran guru, dan modul akademik multi-tenant untuk institusi pendidikan.",
    image: "/images/projects/tams.svg",
    stacks: ["Laravel", "Vue.js", "MySql", "PHP"],
    is_show: true,
    is_featured: true,
    link_demo: null,
    link_github: null,
  },
  {
    id: 3,
    title: "LMS System",
    slug: "lms-system",
    description:
      "Learning Management System modern: course delivery, assessment, progress tracking, dan role-based access untuk sekolah/kampus.",
    image: "/images/projects/lms.svg",
    stacks: ["Next.js", "TypeScript", "Laravel", "MySql"],
    is_show: true,
    is_featured: true,
    link_demo: null,
    link_github: null,
  },
  {
    id: 4,
    title: "Apotik Sehat",
    slug: "apotik-sehat",
    description:
      "Platform apotek digital: inventori obat, resep, transaksi, dan laporan stok real-time untuk operasional apotek modern.",
    image: "/images/projects/apotik.svg",
    stacks: ["Laravel", "MySql", "JavaScript", "TailwindCSS"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 5,
    title: "Yarsha Absensi",
    slug: "yarsha-absensi",
    description:
      "Sistem absensi & kehadiran dengan alur approval, rekap otomatis, dan dashboard HR untuk organisasi pesantren/sekolah.",
    image: "/images/projects/absensi.svg",
    stacks: ["Laravel", "PHP", "MySql", "Vue.js"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 6,
    title: "MyHafiz",
    slug: "myhafiz",
    description:
      "Aplikasi monitoring hafalan Al-Qur'an: setoran, muroja'ah, progres santri, dan laporan wali/pengajar.",
    image: "/images/projects/myhafiz.svg",
    stacks: ["Laravel", "MySql", "TailwindCSS", "JavaScript"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 7,
    title: "MySantri",
    slug: "mysantri",
    description:
      "Portal manajemen santri: data akademik, asrama, keuangan, dan komunikasi orang tua dalam satu ekosistem.",
    image: "/images/projects/mysantri.svg",
    stacks: ["Laravel", "PHP", "MySql", "Bootstrap"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 8,
    title: "Setara Space",
    slug: "setara-space",
    description:
      "Platform kolaborasi & workspace digital dengan modul konten, membership, dan integrasi layanan internal.",
    image: "/images/projects/setara.svg",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Supabase"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 9,
    title: "Glopin",
    slug: "glopin",
    description:
      "Aplikasi fintech/poin loyalty: dompet digital, reward, dan dashboard transaksi dengan arsitektur API-first.",
    image: "/images/projects/glopin.svg",
    stacks: ["Laravel", "MySql", "JavaScript", "Docker"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 10,
    title: "CF Temp Mail Worker",
    slug: "cf-temp-mail-worker",
    description:
      "Edge worker temporary email di Cloudflare Workers—routing inbound, storage ringan, dan API konsumsi email.",
    image: "/images/projects/cfworker.svg",
    stacks: ["TypeScript", "JavaScript", "Node.js"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 11,
    title: "Corextor Platform",
    slug: "corextor-platform",
    description:
      "Platform multi-service untuk operasional bisnis: modul admin, API gateway pattern, dan dashboard monitoring.",
    image: "/images/projects/corextor.svg",
    stacks: ["Next.js", "TypeScript", "Laravel", "PostgreSql"],
    is_show: true,
    is_featured: false,
    link_demo: null,
    link_github: null,
  },
  {
    id: 12,
    title: "Portfolio CMS",
    slug: "taufiq-porto",
    description:
      "Personal portfolio Next.js dengan admin CMS, Supabase, lanyard 3D, dan i18n—deployed on Vercel.",
    image: "/images/projects/porto.svg",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Supabase", "Framer Motion"],
    is_show: true,
    is_featured: true,
    link_demo: "https://taufiqriza.vercel.app",
    link_github: "https://github.com/taufiqriza/taufiqriza",
  },
];
